# Упражнения "Работа с тензорами в PyTorch"

Задание 1. Импортируйте PyTorch и посмотрите версию.

In [86]:
import torch

In [87]:
import torch
print(torch.__version__)


2.9.0+cpu


Задание 2. Создайте одномерный тензор чисел от 0 до 9.

Желаемый результат:

> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
# ваш код здесь
vector = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
vector_tensor = torch.tensor(vector)
print(vector_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Задание 3. Для тензора, созданного в задании 2, выведите


*   тип элементов
*   размер
*   количество размерностей



In [89]:
# ваш код здесь
print(
    f"Тензор:\n{vector_tensor}",
    f"Тип элемента                  --> {vector_tensor.dtype}",
    f"Размеры тензора               --> {vector_tensor.shape}",
    f"Количество размерностей       --> {vector_tensor.dim()}",
    sep="\n\n",
)

Тензор:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Тип элемента                  --> torch.int64

Размеры тензора               --> torch.Size([10])

Количество размерностей       --> 1


Задание 4. Разделите тензор из задания 2 на две половины (левую - начало тензора и правую - его конец). Выведите обе эти половины.

In [90]:
# ваш код здесь
vector_tensor1=vector_tensor[:5]
vector_tensor2=vector_tensor[5:]
print(
    f"Левая половина --> {vector_tensor1}\n"
    f"Правая половина --> {vector_tensor2}"
)

Левая половина --> tensor([0, 1, 2, 3, 4])
Правая половина --> tensor([5, 6, 7, 8, 9])


Задание 5. Создайте вещественный массив размером $3 \times 4$, в котором все элементы равны 1.

In [91]:
# ваш код здесь
matrix = [[1., 1., 1., 1.], [1., 1., 1., 1.], [1., 1., 1., 1.]]
print(matrix)

[[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]


Задание 6. Создайте логический массив размером $5 \times 2$, в котором все элементы равны True.

In [92]:
# ваш код здесь
matrix = [[True, True, True, True, True], [True, True, True, True, True]]

Задание 7. Создайте одномерный тензор с последовательностью вещественных чисел от 1 до 15 включительно, в котором каждый следующий элемент отличается от предыдущего на 0.5

In [93]:
# ваш код здесь
tensor=torch.arange(1, 15.5, 0.5,dtype=torch.double)
print(tensor)

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000], dtype=torch.float64)


Задание 8. Создайте одномерный тензор, в котором ровно 20 значений. Первой значение 1, последнее значение 10, а расстояние между каждыми двумя соседними элементами одинаково.

In [94]:
# ваш код здесь
torch.linspace(1, 10, 20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

Задание 9. Создайте двумерный тензор случайных вещественных значений размером $4 \times 3$ из равномерного распределения на полуинтервале [0, 1).

In [95]:
# ваш код здесь
torch.rand(4, 3, dtype=torch.float32)


tensor([[0.4810, 0.1239, 0.8225],
        [0.5606, 0.9905, 0.2241],
        [0.9831, 0.9384, 0.9956],
        [0.5697, 0.2803, 0.8449]])

Задание 10. Создайте одномерный тензор 100 случайных "школьных оценок", а именно целых значений из промежутка от 3 до 5 включительно.

In [96]:
# ваш код здесь
sh=torch.randint(
    3,
    6,
    (1, 100),
)
print(sh)



tensor([[4, 4, 3, 3, 3, 4, 5, 3, 3, 4, 3, 5, 4, 5, 5, 5, 5, 5, 4, 5, 4, 3, 5, 3,
         5, 4, 4, 4, 4, 3, 5, 3, 5, 3, 3, 5, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 5, 4,
         4, 3, 5, 4, 4, 5, 4, 5, 5, 3, 4, 4, 5, 4, 5, 3, 4, 3, 5, 5, 5, 3, 4, 4,
         4, 4, 4, 3, 4, 4, 4, 3, 5, 5, 3, 5, 3, 5, 5, 3, 5, 3, 5, 4, 5, 4, 5, 4,
         4, 5, 5, 3]])


Задание 11. Для тензора "школьных отенок", созданного в задании 10, посчитайте и выведите минимум, максимум и среднее арифметическое.

In [97]:
# ваш код здесь
print(f"Изначальный вектор:\n{sh}\n",
      f"Минимальное значение:{sh.min()}\n",
      f"Максимальное значение:{sh.max()}\n",
      f"Среднее арифметическое элементов:{sh.float().mean()}",
      )

Изначальный вектор:
tensor([[4, 4, 3, 3, 3, 4, 5, 3, 3, 4, 3, 5, 4, 5, 5, 5, 5, 5, 4, 5, 4, 3, 5, 3,
         5, 4, 4, 4, 4, 3, 5, 3, 5, 3, 3, 5, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 5, 4,
         4, 3, 5, 4, 4, 5, 4, 5, 5, 3, 4, 4, 5, 4, 5, 3, 4, 3, 5, 5, 5, 3, 4, 4,
         4, 4, 4, 3, 4, 4, 4, 3, 5, 5, 3, 5, 3, 5, 5, 3, 5, 3, 5, 4, 5, 4, 5, 4,
         4, 5, 5, 3]])
 Минимальное значение:3
 Максимальное значение:5
 Среднее арифметическое элементов:4.019999980926514


Задание 12. Создайте создайте булеву маску для массива "школьных оценок" из задания 10, в которой True будет стоять для первых 5 оценок и для последних 5 оценок, а остальные значения будут False.

In [98]:
# ваш код здесь
mask = torch.zeros(100, dtype=torch.bool)
mask[:5] = True
mask[-5:] = True
print(mask)


tensor([ True,  True,  True,  True,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True,  True,  True,  True,  True])


Задание 13. Отфильтруйте тензор "школьных оценок", созданный в задании 10, с помощью маски, созданной в задании 12, оставив тем самым только первые и последние пять оценок.

In [99]:
# ваш код здесь
filtered_scores = sh.squeeze()[mask]
print(filtered_scores)

tensor([4, 4, 3, 3, 3, 4, 4, 5, 5, 3])


Задание 14. Создайте маску для тензора "школьных оценок", в которой для каждой "пятерки" будет стоять True, а для остальных значений будет стоять False.

In [100]:
# ваш код здесь
sh > 4

tensor([[False, False, False, False, False, False,  True, False, False, False,
         False,  True, False,  True,  True,  True,  True,  True, False,  True,
         False, False,  True, False,  True, False, False, False, False, False,
          True, False,  True, False, False,  True, False, False, False, False,
         False, False, False, False, False, False,  True, False, False, False,
          True, False, False,  True, False,  True,  True, False, False, False,
          True, False,  True, False, False, False,  True,  True,  True, False,
         False, False, False, False, False, False, False, False, False, False,
          True,  True, False,  True, False,  True,  True, False,  True, False,
          True, False,  True, False,  True, False, False,  True,  True, False]])

Задание 15. Извлеките все "пятерки" из тензора "школьных отенок", созданного в задании 10, и занесите их в новый тензор.


In [101]:
# ваш код здесь
fives = sh[sh == 5]
print(fives)
print(f"Количество пятерок: {len(fives)}")

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
Количество пятерок: 34


Задание 16. Преобразуйте тензор "школьных оценок" в двумерный тензор с 5 строками размером $5 \times 20$.


In [102]:
# ваш код здесь
scores_2d = sh.reshape(5, 20)
print(scores_2d.shape)
print(scores_2d)

torch.Size([5, 20])
tensor([[4, 4, 3, 3, 3, 4, 5, 3, 3, 4, 3, 5, 4, 5, 5, 5, 5, 5, 4, 5],
        [4, 3, 5, 3, 5, 4, 4, 4, 4, 3, 5, 3, 5, 3, 3, 5, 3, 3, 3, 3],
        [3, 3, 4, 4, 3, 3, 5, 4, 4, 3, 5, 4, 4, 5, 4, 5, 5, 3, 4, 4],
        [5, 4, 5, 3, 4, 3, 5, 5, 5, 3, 4, 4, 4, 4, 4, 3, 4, 4, 4, 3],
        [5, 5, 3, 5, 3, 5, 5, 3, 5, 3, 5, 4, 5, 4, 5, 4, 4, 5, 5, 3]])


Задание 17. Выполните стыковку тензоров a и b по вертикали.

Вход:

> a = torch.arange(2, 10, 2).reshape(2, -1)

> b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $4 \times 5$.


In [103]:
# ваш код здесь
a = torch.arange(2, 12).reshape(2, -1)
b = torch.ones(1, 10).reshape(2, -1)

result_vertical = torch.vstack([a, b])
print(result_vertical)
print(f"Размер: {result_vertical.shape}")

tensor([[ 2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])
Размер: torch.Size([4, 5])


Задание 18. Выполните стыковку тензоров a и b по горизонтали.

Вход:

a = torch.arange(2, 10, 2).reshape(2, -1)

b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $2 \times 10$.

In [104]:
# ваш код здесь
a = torch.arange(2, 10, 2).reshape(2, -1)
b = torch.ones(1, 10).reshape(2, -1)
result_horizontal = torch.hstack([a, b])
print(result_horizontal)
print(f"Размер: {result_horizontal.shape}")

tensor([[2., 4., 1., 1., 1., 1., 1.],
        [6., 8., 1., 1., 1., 1., 1.]])
Размер: torch.Size([2, 7])


Задание 19. Получите все элементы от 5 до 10 в тензоре a.

Вход:

> a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

Желаемый результат:

> tensor([6, 9, 10])

In [105]:
# ваш код здесь
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
result = a[(a >= 5) & (a <= 10)]
print(result)


tensor([ 6,  9, 10])


Задание 20. Вывести первую строку матрицы из задания 18.

In [106]:
# ваш код здесь
first_row = result_horizontal[0]
print(first_row)


tensor([2., 4., 1., 1., 1., 1., 1.])


Задание 21. Вывести последний столбец матрицы из задания 17.

In [107]:
# ваш код здесь
last_column = result_vertical[:, -1]
print(last_column)

tensor([ 6., 11.,  1.,  1.])


Задание 22. Вывести центральную часть матрицы из задания 17 (размерностью $2 \times 3$).

In [108]:
# ваш код здесь
center = result_vertical[1:3, 1:4]
print(center)


tensor([[ 8.,  9., 10.],
        [ 1.,  1.,  1.]])


Задание 23. Вставить в двумерный терзор из задания 17 строку из минимального элемента перед первой строкой.

In [109]:
# ваш код здесь
min_val = result_vertical.min()
new_row = torch.full((1, result_vertical.shape[1]), min_val, dtype=result_vertical.dtype)
result_with_min_row = torch.vstack([new_row, result_vertical])
print(result_with_min_row)

tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])


Задание 24.	В тензоре, полученном при выполнении задания 23, каждый элемент заменить его корнем квадратным.

In [110]:
# ваш код здесь
result_sqrt = torch.sqrt(result_with_min_row)
print(result_sqrt)

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.4142, 1.7321, 2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000, 3.1623, 3.3166],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])


Задание 25.	Заменить в тензоре из задания 18 все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.

In [111]:
# ваш код здесь
modified = result_horizontal.clone()
mask = (modified % 2 == 0) | (modified % 3 == 0)
modified[mask] = 1
print(modified)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])
